### ISSUE TITLE
Oauth credentials stop working intermittently

### ISSUE THREAD

**Issue by martina-equinix** [PagerDuty/backstage-plugin#144]
**Describe the bug**

I have one pagerduty account configured through scoped oauth credentials and I am noticing that these credentials stop working after some time until I restart the backstage backend.

Initially, it can fetch services via the `pagerduty.com/service-id` annotation but after a day or two, when I visit the same component I get `Missing or invalid PagerDuty Token` and a `401` error with the following message:

```
{
    "errors": [
        "Failed to get service. Caller did not supply credentials or did not provide the correct credentials."
    ]
}
```

When I see this, if I just restart Backstage it starts working again with no issues.

The configuration I am using is:

```
pagerDuty:
  oauth:
    clientId: ${PD_CLIENT_ID}
    clientSecret: ${PD_CLIENT_SECRET}
    subDomain: ${PD_ACCOUNT_SUBDOMAIN} # just the subdomain part as stated in the docs
```

**Expected behavior**
The pagerduty integration works continuously without having to restart the backend.

**Screenshots**

![Screenshot 2024-10-21 at 11 54 31 AM](https://github.com/user-attachments/assets/f33d79c5-260b-4a6a-860a-888f7ac563fb)

**versions**

```
@pagerduty/backstage-plugin-backend: 0.9.1
@pagerduty/backstage-plugin-common: 0.2.1
@pagerduty/backstage-plugin: 0.15.1

backstage version: "1.31.1"
```

**Additional context**
